// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using invoice_v1.src.Infrastructure.Data;

#nullable disable

namespace invoice_v1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.FileChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FileId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GoogleDriveModifiedTime")
                        .HasColumnType("timestamptz");

                    b.Property<string>("MimeType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Processed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTime?>("SecurityCheckedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SecurityFailReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecurityStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pending");

                    b.Property<Guid?>("UploadedByVendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChangeType")
                        .HasDatabaseName("ix_file_change_logs_change_type");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_file_change_logs_file_id");

                    b.HasIndex("Processed")
                        .HasDatabaseName("ix_file_change_logs_processed");

                    b.HasIndex("SecurityStatus")
                        .HasDatabaseName("ix_file_change_logs_security_status");

                    b.HasIndex("UploadedByVendorId")
                        .HasDatabaseName("ix_file_change_logs_uploaded_by_vendor_id");

                    b.HasIndex("Processed", "DetectedAt")
                        .HasDatabaseName("ix_file_change_logs_processed_detected_at");

                    b.ToTable("file_change_logs", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvalidInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid");

                    b.Property<JsonDocument>("Reason")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_invalid_invoices_created_at");

                    b.HasIndex("FileId")
                        .HasDatabaseName("ix_invalid_invoices_file_id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("ix_invalid_invoices_job_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_invalid_invoices_vendor_id");

                    b.ToTable("invalid_invoices", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BalanceDue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BillToName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DriveFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<JsonDocument>("ExtractedDataJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ShipMode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShipToCity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ShipToCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShipToState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Terms")
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("UploadedByVendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_invoices_created_at");

                    b.HasIndex("DriveFileId")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_drive_file_id_unique");

                    b.HasIndex("InvoiceDate")
                        .HasDatabaseName("ix_invoices_invoice_date");

                    b.HasIndex("InvoiceNumber")
                        .HasDatabaseName("ix_invoices_invoice_number");

                    b.HasIndex("UploadedByVendorId")
                        .HasDatabaseName("ix_invoices_uploaded_by_vendor_id");

                    b.HasIndex("InvoiceDate", "TotalAmount")
                        .HasDatabaseName("ix_invoices_date_amount");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvoiceLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_invoice_id");

                    b.HasIndex("ProductGuid")
                        .HasDatabaseName("ix_invoice_lines_product_guid");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_invoice_lines_product_id");

                    b.HasIndex("ProductGuid", "InvoiceId")
                        .HasDatabaseName("ix_invoice_lines_product_invoice");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.JobQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<JsonDocument>("ErrorMessage")
                        .HasColumnType("jsonb");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("timestamptz");

                    b.Property<JsonDocument>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<JsonDocument>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_job_queues_created_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_queues_status");

                    b.HasIndex("Status", "LockedAt")
                        .HasDatabaseName("ix_job_queues_status_locked_at");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_job_queues_status_next_retry_at");

                    b.ToTable("job_queues", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal?>("DefaultUnitRate")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("InvoiceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("LastSoldDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PrimaryCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecondaryCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("TotalQuantitySold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,4)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalRevenue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_products_category");

                    b.HasIndex("LastSoldDate")
                        .HasDatabaseName("ix_products_last_sold_date");

                    b.HasIndex("PrimaryCategory")
                        .HasDatabaseName("ix_products_primary_category");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasDatabaseName("ix_products_product_id_unique");

                    b.HasIndex("ProductName")
                        .HasDatabaseName("ix_products_product_name");

                    b.HasIndex("TotalRevenue")
                        .HasDatabaseName("ix_products_total_revenue");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("FailedLoginCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsSoftDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_unique");

                    b.HasIndex("IsSoftDeleted")
                        .HasDatabaseName("ix_users_is_soft_deleted");

                    b.HasIndex("Role")
                        .HasDatabaseName("ix_users_role");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.HasIndex("Role", "Status")
                        .HasDatabaseName("ix_users_role_status");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("invoice_v1.src.Domain.Entities.User", "UploadedByVendor")
                        .WithMany()
                        .HasForeignKey("UploadedByVendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedByVendor");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.InvoiceLine", b =>
                {
                    b.HasOne("invoice_v1.src.Domain.Entities.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("invoice_v1.src.Domain.Entities.Product", "Product")
                        .WithMany("InvoiceLines")
                        .HasForeignKey("ProductGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("invoice_v1.src.Domain.Entities.Product", b =>
                {
                    b.Navigation("InvoiceLines");
                });
#pragma warning restore 612, 618
        }
    }
}
